# -*- coding: utf-8 -*-
"""GenAI project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11DbolHc2-H7XRLsXC0YStZHUdTf36zAq
"""

!pip install transformers

from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# Load pre-trained model and tokenizer
tokenizer = AutoTokenizer.from_pretrained("microsoft/DialoGPT-small")
model = AutoModelForCausalLM.from_pretrained("microsoft/DialoGPT-small")

# Chat history
chat_history_ids = None
step = 0

print("ChatBot: Hello! I'm your Gen AI assistant. Type 'quit' to exit.")

while True:
    # Get user input
    user_input = input("You: ")
    if user_input.lower() == "quit":
        print("ChatBot: Goodbye!")
        break

    # Encode user input
    new_input_ids = tokenizer.encode(user_input + tokenizer.eos_token, return_tensors='pt')

    # Append to chat history (if not first turn)
    bot_input_ids = torch.cat([chat_history_ids, new_input_ids], dim=-1) if step > 0 else new_input_ids

    # Generate response
    chat_history_ids = model.generate(bot_input_ids, max_length=1000, pad_token_id=tokenizer.eos_token_id)

    # Decode and print response
    response = tokenizer.decode(chat_history_ids[:, bot_input_ids.shape[-1]:][0], skip_special_tokens=True)
    print(f"ChatBot: {response}")
    step += 1

